export default {
  // -----// LOGIN //-----//
  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  // -----// LOGIN_BY_SMS //-----//
  LOGIN_BY_SMS_START: 'LOGIN_BY_SMS_START',
  LOGIN_BY_SMS_SUCCESS: 'LOGIN_BY_SMS_SUCCESS',
  LOGIN_BY_SMS_FAILURE: 'LOGIN_BY_SMS_FAILURE',

  // -----// SET_MODAL //-----//
  SET_MODAL_START: 'SET_MODAL_START',
  SET_MODAL_SUCCESS: 'SET_MODAL_SUCCESS',
  SET_MODAL_FAILURE: 'SET_MODAL_FAILURE',

  // -----// LOGOUT //-----//
  LOGOUT_START: 'LOGOUT_START',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',

  // ----- // RESET_PASSWORD // ----- //
  RESET_PASSWORD_START: 'RESET_PASSWORD_START',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',

  // ----- // CHANGE_PASSWORD // ----- //
  CHANGE_PASSWORD_START: 'CHANGE_PASSWORD_START',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',

  // ----- // CHANGE_PASSWORD // ----- //
  CHANGE_USER_PASSWORD_START: 'CHANGE_USER_PASSWORD_START',
  CHANGE_USER_PASSWORD_SUCCESS: 'CHANGE_USER_PASSWORD_SUCCESS',
  CHANGE_USER_PASSWORD_FAILURE: 'CHANGE_USER_PASSWORD_FAILURE',

  // ----- // SIGNUP // ----- //
  SIGNUP_START: 'SIGNUP_START',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',

  // -----// POST_RESEND_SMS_CODE //-----//
  POST_RESEND_SMS_CODE_START: 'POST_RESEND_SMS_CODE_START',
  POST_RESEND_SMS_CODE_SUCCESS: 'POST_RESEND_SMS_CODE_SUCCESS',
  POST_RESEND_SMS_CODE_FAILURE: 'POST_RESEND_SMS_CODE_FAILURE',

  // ----- // SET_LANGUAGE // ----- //
  SET_LANGUAGE_START: 'SET_LANGUAGE_START',
  SET_LANGUAGE_SUCCESS: 'SET_LANGUAGE_SUCCESS',
  SET_LANGUAGE_FAILURE: 'SET_LANGUAGE_FAILURE',

  // ----- // SOCKET // ----- //
  SOCKET_OPEN: 'SOCKET_OPEN',
  SOCKET_CLOSE: 'SOCKET_CLOSE',
  SOCKET_CONNECTED: 'SOCKET_CONNECTED',
  SOCKET_SEND_CHANNEL: 'SOCKET_SEND_CHANNEL',
  SOCKET_DISCONNECTED: 'SOCKET_DISCONNECTED',

  // ----- // CONFIRM_EMAIL // ----- //
  CONFIRM_EMAIL_START: 'CONFIRM_EMAIL_START',
  CONFIRM_EMAIL_SUCCESS: 'CONFIRM_EMAIL_SUCCESS',
  CONFIRM_EMAIL_FAILURE: 'CONFIRM_EMAIL_FAILURE',

  /**
   * TOKENS
   */

  // ----- // GET_TOKENS // ----- //
  GET_TOKENS_START: 'GET_TOKENS_START',
  GET_TOKENS_SUCCESS: 'GET_TOKENS_SUCCESS',
  GET_TOKENS_FAILURE: 'GET_TOKENS_FAILURE',

  // ----- // CREATE_TOKENS // ----- //
  CREATE_TOKENS_START: 'CREATE_TOKENS_START',
  CREATE_TOKENS_SUCCESS: 'CREATE_TOKENS_SUCCESS',
  CREATE_TOKENS_FAILURE: 'CREATE_TOKENS_FAILURE',

  // ----- // DISABLE_TOKENS // ----- //
  DISABLE_TOKENS_START: 'DISABLE_TOKENS_START',
  DISABLE_TOKENS_SUCCESS: 'DISABLE_TOKENS_SUCCESS',
  DISABLE_TOKENS_FAILURE: 'DISABLE_TOKENS_FAILURE',

  // ----- // DELETE_TOKENS // ----- //
  DELETE_TOKENS_START: 'DELETE_TOKENS_START',
  DELETE_TOKENS_SUCCESS: 'DELETE_TOKENS_SUCCESS',
  DELETE_TOKENS_FAILURE: 'DELETE_TOKENS_FAILURE',

  // ----- // UPDATE_TOKENS // ----- //
  UPDATE_USER_TOKEN_START: 'UPDATE_USER_TOKEN_START',
  UPDATE_USER_TOKEN_SUCCESS: 'UPDATE_USER_TOKEN_SUCCESS',

  // ----- // RESET_PASSWORD // ----- //
  USERS_RESET_PASSWORD_START: 'USERS_RESET_PASSWORD_START',
  USERS_RESET_PASSWORD_SUCCESS: 'USERS_RESET_PASSWORD_SUCCESS',
  USERS_RESET_PASSWORD_FAILURE: 'USERS_RESET_PASSWORD_FAILURE',

  // ----- // RESET 2FA // ----- //
  RESET_2FA_START: 'RESET_2FA_START',
  RESET_2FA_SUCCESS: 'RESET_2FA_SUCCESS',
  RESET_2FA_FAILURE: 'RESET_2FA_FAILURE',

  // ----- // UPLOAD SELFI FOR RESET 2FA // ----- //
  UPLOAD_SELFI_RESET_2FA_START: 'UPLOAD_SELFI_RESET_2FA_START',
  UPLOAD_SELFI_RESET_2FA_SUCCESS: 'UPLOAD_SELFI_RESET_2FA_SUCCESS',
  UPLOAD_SELFI_RESET_2FA_FAILURE: 'UPLOAD_SELFI_RESET_2FA_FAILURE',

  // ----- // ENABLE GOOGLE 2FA // ----- //
  ENABLE_GOOGLE_2FA_START: 'ENABLE_GOOGLE_2FA_START',
  ENABLE_GOOGLE_2FA_SUCCESS: 'ENABLE_GOOGLE_2FA_SUCCESS',
  ENABLE_GOOGLE_2FA_FAILURE: 'ENABLE_GOOGLE_2FA_FAILURE',

  // ----- // DISABLE GOOGLE 2FA // ----- //
  DISABLE_GOOGLE_2FA_START: 'DISABLE_GOOGLE_2FA_START',
  DISABLE_GOOGLE_2FA_SUCCESS: 'DISABLE_GOOGLE_2FA_SUCCESS',
  DISABLE_GOOGLE_2FA_FAILURE: 'DISABLE_GOOGLE_2FA_FAILURE',

  // ----- // GET SECRET KEY // ----- //
  GET_SECRET_KEY_START: 'GET_SECRET_KEY_START',
  GET_SECRET_KEY_SUCCESS: 'GET_SECRET_KEY_SUCCESS',
  GET_SECRET_KEY_FAILURE: 'GET_SECRET_KEY_FAILURE',

  // ----- // GET_REFRESH_TOKEN // ----- //
  GET_REFRESH_TOKEN_START: 'GET_REFRESH_TOKEN_START',
  GET_REFRESH_TOKEN_SUCCESS: 'GET_REFRESH_TOKEN_SUCCESS',
  GET_REFRESH_TOKEN_FAILURE: 'GET_REFRESH_TOKEN_FAILURE',

  // ----- // GET USER DATA // ----- //
  GET_USER_DATA_START: 'GET_USER_DATA_START',
  GET_USER_DATA_SUCCESS: 'GET_USER_DATA_SUCCESS',
  GET_USER_DATA_FAILURE: 'GET_USER_DATA_FAILURE',

  // ----- // UPDATE USER DATA // ----- //
  UPDATE_USER_DATA_START: 'UPDATE_USER_DATA_START',
  UPDATE_USER_DATA_SUCCESS: 'UPDATE_USER_DATA_SUCCESS',
  UPDATE_USER_DATA_FAILURE: 'UPDATE_USER_DATA_FAILURESS',

  // ----- // GENERATE_GOOGLE_SECRET // ----- //
  GENERATE_GOOGLE_SECRET_START: 'GENERATE_GOOGLE_SECRET_START',
  GENERATE_GOOGLE_SECRET_SUCCESS: 'GENERATE_GOOGLE_SECRET_SUCCESS',
  GENERATE_GOOGLE_SECRET_FAILURE: 'GENERATE_GOOGLE_SECRET_FAILURE',

  // ----- // ENABLE_GOOGLE_SECRET // ----- //
  ENABLE_GOOGLE_SECRET_START: 'ENABLE_GOOGLE_SECRET_START',
  ENABLE_GOOGLE_SECRET_SUCCESS: 'ENABLE_GOOGLE_SECRET_SUCCESS',
  ENABLE_GOOGLE_SECRET_FAILURE: 'ENABLE_GOOGLE_SECRET_FAILURE',

  // ----- // DISABLE_GOOGLE_SECRET // ----- //
  DISABLE_GOOGLE_SECRET_START: 'DISABLE_GOOGLE_SECRET_START',
  DISABLE_GOOGLE_SECRET_SUCCESS: 'DISABLE_GOOGLE_SECRET_SUCCESS',
  DISABLE_GOOGLE_SECRET_FAILURE: 'DISABLE_GOOGLE_SECRET_FAILURE',

  // ----- // GET_SMS_CODE // ----- //
  GET_SMS_CODE_START: 'GET_SMS_CODE_START',
  GET_SMS_CODE_SUCCESS: 'GET_SMS_CODE_SUCCESS',
  GET_SMS_CODE_FAILURE: 'GET_SMS_CODE_FAILURE',

  GET_EMAIL_CODE_START: 'GET_EMAIL_CODE_START',
  GET_EMAIL_CODE_SUCCESS: 'GET_EMAIL_CODE_SUCCESS',
  GET_EMAIL_CODE_FAILURE: 'GET_EMAIL_CODE_FAILURE',

  // ----- // SET_ANTIPHISHING_PHRASE // ----- //
  SET_ANTIPHISHING_PHRASE_START: 'SET_ANTIPHISHING_PHRASE_START',
  SET_ANTIPHISHING_PHRASE_SUCCESS: 'SET_ANTIPHISHING_PHRASE_SUCCESS',
  SET_ANTIPHISHING_PHRASE_FAILURE: 'SET_ANTIPHISHING_PHRASE_FAILURE',

  // ----- // CHANGE_ANTIPHISHING_PHRASE // ----- //
  CHANGE_ANTIPHISHING_PHRASE_START: 'CHANGE_ANTIPHISHING_PHRASE_START',
  CHANGE_ANTIPHISHING_PHRASE_SUCCESS: 'CHANGE_ANTIPHISHING_PHRASE_SUCCESS',
  CHANGE_ANTIPHISHING_PHRASE_FAILURE: 'CHANGE_ANTIPHISHING_PHRASE_FAILURE',

  // ----- // ENABLE_2FA_PHONE // ----- //
  ENABLE_2FA_PHONE_START: 'ENABLE_2FA_PHONE_START',
  ENABLE_2FA_PHONE_SUCCESS: 'ENABLE_2FA_PHONE_SUCCESS',
  ENABLE_2FA_PHONE_FAILURE: 'ENABLE_2FA_PHONE_FAILURE',

  // ----- // DISABLE_2FA_PHONE // ----- //
  DISABLE_2FA_PHONE_START: 'DISABLE_2FA_PHONE_START',
  DISABLE_2FA_PHONE_SUCCESS: 'DISABLE_2FA_PHONE_SUCCESS',
  DISABLE_2FA_PHONE_FAILURE: 'DISABLE_2FA_PHONE_FAILURE',

  // ----- // GET_LOGIN_RECORDS_START // ----- //
  GET_LOGIN_RECORDS_START: 'GET_LOGIN_RECORDS_START',
  GET_LOGIN_RECORDS_SUCCESS: 'GET_LOGIN_RECORDS_SUCCESS',
  GET_LOGIN_RECORDS_FAILURE: 'GET_LOGIN_RECORDS_FAILURE',

  // ----- // GET_DEVICES_LIST // ----- //
  GET_DEVICES_LIST_START: 'GET_DEVICES_LIST_START',
  GET_DEVICES_LIST_SUCCESS: 'GET_DEVICES_LIST_SUCCESS',
  GET_DEVICES_LIST_FAILURE: 'GET_DEVICES_LIST_FAILURE',

  // ----- // DELETE_DEVICES_LIST // ----- //
  DELETE_DEVICES_LIST_START: 'DELETE_DEVICES_LIST_START',
  DELETE_DEVICES_LIST_SUCCESS: 'DELETE_DEVICES_LIST_SUCCESS',
  DELETE_DEVICES_LIST_FAILURE: 'DELETE_DEVICES_LIST_FAILURE',

  // ----- // SEND SUPPORT DATA // ----- //
  SEND_SUPPORT_DATA_START: 'SEND_SUPPORT_DATA_START',
  SEND_SUPPORT_DATA_SUCCESS: 'SEND_SUPPORT_DATA_SUCCESS',
  SEND_SUPPORT_DATA_FAILURE: 'SEND_SUPPORT_DATA_FAILURE',

  // ----- // CONTACT US SEND DATA // ----- //
  CONTACT_US_SEND_START: 'CONTACT_US_SEND_START',
  CONTACT_US_SEND_SUCCESS: 'CONTACT_US_SEND_SUCCESS',
  CONTACT_US_SEND_FAILURE: 'CONTACT_US_SEND_FAILURE',

  RESET_2FA_SEND_FORM_START: 'RESET_2FA_SEND_FORM_START',
  RESET_2FA_SEND_FORM_SUCCESS: 'RESET_2FA_SEND_FORM_SUCCESS',
  RESET_2FA_SEND_FORM_FAILURE: 'RESET_2FA_SEND_FORM_FAILURE',

  // ----- // SET_CURRENT_PAIR // ----- //
  SET_CURRENT_PAIR_START: 'SET_CURRENT_PAIR_START',
  SET_CURRENT_PAIR_SUCCESS: 'SET_CURRENT_PAIR_SUCCESS',
  SET_CURRENT_PAIR_FAILURE: 'SET_CURRENT_PAIR_FAILURE',

  // ----- // EXCHANGE_RATE // ----- //
  EXCHANGE_RATE_START: 'EXCHANGE_RATE_START',
  EXCHANGE_RATE_SUCCESS: 'EXCHANGE_RATE_SUCCESS',
  EXCHANGE_RATE_FAILURE: 'EXCHANGE_RATE_FAILURE',

  // ----- // EXCHANGE // ----- //
  EXCHANGE_START: 'EXCHANGE_START',
  EXCHANGE_SUCCESS: 'EXCHANGE_SUCCESS',
  EXCHANGE_FAILURE: 'EXCHANGE_FAILURE',

  // ----- // GET_EXCHANGE_HISTORY // ----- //
  GET_EXCHANGE_HISTORY_START: 'GET_EXCHANGE_HISTORY_START',
  GET_EXCHANGE_HISTORY_SUCCESS: 'GET_EXCHANGE_HISTORY_SUCCESS',
  GET_EXCHANGE_HISTORY_FAILURE: 'GET_EXCHANGE_HISTORY_FAILURE',
  CLEAR_EXCHANGE_HISTORY: 'CLEAR_EXCHANGE_HISTORY',

  // GET SECOND ASSETS
  GET_SECOND_ASSETS_START: 'GET_SECOND_ASSETS_START',
  GET_SECOND_ASSETS_SUCCESS: 'GET_SECOND_ASSETS_SUCCESS',
  GET_SECOND_ASSETS_FAILURE: 'GET_SECOND_ASSETS_FAILURE',

  // ----- // GET_ASSETS // ----- //
  GET_ASSETS_START: 'GET_ASSETS_START',
  GET_ASSETS_SUCCESS: 'GET_ASSETS_SUCCESS',
  GET_ASSETS_FAILURE: 'GET_ASSETS_FAILURE',

  /**
   * SPOT TRADESwa
   */
  // ----- // GET_ORDERS_LIST // ----- //
  SPOT_GET_ORDERS_LIST_START: 'SPOT_GET_ORDERS_LIST_START',
  SPOT_GET_ORDERS_LIST_SUCCESS: 'SPOT_GET_ORDERS_LIST_SUCCESS',
  SPOT_GET_ORDERS_LIST_FAILURE: 'SPOT_GET_ORDERS_LIST_FAILURE',
  UPDATE_SPOT_OPEN_ORDERS: 'UPDATE_SPOT_OPEN_ORDERS',
  // ----- // Swap_ORDERS_LIST // ----- //
  Swap_GET_ORDERS_LIST_START: 'Swap_GET_ORDERS_LIST_START',
  Swap_GET_ORDERS_LIST_SUCCESS: 'Swap_GET_ORDERS_LIST_SUCCESS',
  Swap_GET_ORDERS_LIST_FAILURE: 'Swap_GET_ORDERS_LIST_FAILURE',
  Swap_SPOT_OPEN_ORDERS: 'Swap_SPOT_OPEN_ORDERS',

  // ----- // CANCEL_OPEN_ORDER // ----- //
  SPOT_CANCEL_OPEN_ORDER_START: 'SPOT_CANCEL_OPEN_ORDER_START',
  SPOT_CANCEL_OPEN_ORDER_SUCCESS: 'SPOT_CANCEL_OPEN_ORDER_SUCCESS',
  SPOT_CANCEL_OPEN_ORDER_FAILURE: 'SPOT_CANCEL_OPEN_ORDER_FAILURE',

  // ----- // CANCEL_ALL_ORDERS // ----- //
  SPOT_CANCEL_ALL_ORDERS_START: 'SPOT_CANCEL_ALL_ORDERS_START',
  SPOT_CANCEL_ALL_ORDERS_SUCCESS: 'SPOT_CANCEL_ALL_ORDES_SUCCESS',
  SPOT_CANCEL_ALL_ORDERS_FAILURE: 'SPOT_CANCEL_ALL_ORDERS_FAILURE',

  // ----- // CANCEL_ALL_ASSETS_ORDERS // ----- //
  SPOT_CANCEL_ALL_ASSETS_ORDERS_START: 'SPOT_CANCEL_ALL_ASSETS_ORDERS_START',
  SPOT_CANCEL_ALL_ASSETS_ORDERS_SUCCESS:
    'SPOT_CANCEL_ALL_ASSETS_ORDERS_SUCCESS',
  SPOT_CANCEL_ALL_ASSETS_ORDERS_FAILURE:
    'SPOT_CANCEL_ALL_ASSETS_ORDERS_FAILURE',

  // ----- // GET_ORDERS_HISTORY // ----- //
  SPOT_GET_ORDERS_HISTORY_START: 'SPOT_GET_ORDERS_HISTORY_START',
  SPOT_GET_ORDERS_HISTORY_SUCCESS: 'SPOT_GET_ORDERS_HISTORY_SUCCESS',
  SPOT_GET_ORDERS_HISTORY_FAILURE: 'SPOT_GET_ORDERS_HISTORY_FAILURE',
  UPDATE_SPOT_CLOSED_ORDERS: 'UPDATE_SPOT_CLOSED_ORDERS',

  // ----- // GET_TRADE_HISTORY // ----- //
  SPOT_GET_TRADE_HISTORY_START: 'SPOT_GET_TRADE_HISTORY_START',
  SPOT_GET_TRADE_HISTORY_SUCCESS: 'SPOT_GET_TRADE_HISTORY_SUCCESS',
  SPOT_GET_TRADE_HISTORY_FAILURE: 'SPOT_GET_TRADE_HISTORY_FAILURE',

  // ----- // GET_ORDER_BOOK // ----- //
  SPOT_GET_ORDER_BOOK_START: 'SPOT_GET_ORDER_BOOK_START',
  SPOT_GET_ORDER_BOOK_SUCCESS: 'SPOT_GET_ORDER_BOOK_SUCCESS',
  SPOT_GET_ORDER_BOOK_FAILURE: 'SPOT_GET_ORDER_BOOK_FAILURE',
  UPDATE_SPOT_ORDER_BOOK: 'UPDATE_SPOT_ORDER_BOOK',

  // ----- // GET_RECENT_TRADES // ----- //
  SPOT_GET_RECENT_TRADES_START: 'SPOT_GET_RECENT_TRADES_START',
  SPOT_GET_RECENT_TRADES_SUCCESS: 'SPOT_GET_RECENT_TRADES_SUCCESS',
  SPOT_GET_RECENT_TRADES_FAILURE: 'SPOT_GET_RECENT_TRADES_FAILURE',
  UPDATE_SPOT_RECENT_TRADES: 'UPDATE_SPOT_RECENT_TRADES',

  // ----- // GET_ASSET_PAIRS // ----- //
  GET_ASSET_PAIRS_START: 'GET_ASSET_PAIRS_START',
  GET_ASSET_PAIRS_SUCCESS: 'GET_ASSET_PAIRS_SUCCESS',
  GET_ASSET_PAIRS_FAILURE: 'GET_ASSET_PAIRS_FAILURE',

  // ----- // GET_TOP_PAIRS // ----- //
  GET_TOP_PAIRS_START: 'GET_TOP_PAIRS_START',
  GET_TOP_PAIRS_SUCCESS: 'GET_TOP_PAIRS_SUCCESS',
  GET_TOP_PAIRS_FAILURE: 'GET_TOP_PAIRS_FAILURE',

  // ----- // UPDATE_ASSET_PAIRS // ----- //
  UPDATE_ASSET_PAIRS: 'UPDATE_ASSET_PAIRS',

  // ----- // TEMPORARY_SELECTED_TRADE // ----- //
  TEMPORARY_SELECTED_TRADE: 'TEMPORARY_SELECTED_TRADE',

  // ----- // CREATE_ORDER // ----- //
  CREATE_ORDER_START: 'CREATE_ORDER_START',
  CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS',
  CREATE_ORDER_FAILURE: 'CREATE_ORDER_FAILURE',

  // ----- // CREATE_SPOT_LIMIT_ORDER // ----- //
  CREATE_STOP_LIMIT_ORDER_START: 'CREATE_STOP_LIMIT_ORDER_START',
  CREATE_STOP_LIMIT_ORDER_SUCCESS: 'CREATE_STOP_LIMIT_ORDER_SUCCESS',
  CREATE_STOP_LIMIT_ORDER_FAILURE: 'CREATE_STOP_LIMIT_ORDER_FAILURE',

  // ----- // POST_CALCULATE_MARKET_ORDER // ----- //
  POST_CALCULATE_MARKET_ORDER_START: 'POST_CALCULATE_MARKET_ORDER_START',
  POST_CALCULATE_MARKET_ORDER_SUCCESS: 'POST_CALCULATE_MARKET_ORDER_SUCCESS',
  POST_CALCULATE_MARKET_ORDER_FAILURE: 'POST_CALCULATE_MARKET_ORDER_FAILURE',
  POST_PUBLIC_CALCULATE_MARKET_ORDER_START:
    'POST_PUBLIC_CALCULATE_MARKET_ORDER_START',
  POST_PUBLIC_CALCULATE_MARKET_ORDER_SUCCESS:
    'POST_PUBLIC_CALCULATE_MARKET_ORDER_SUCCESS',
  POST_PUBLIC_CALCULATE_MARKET_ORDER_FAILURE:
    'POST_PUBLIC_CALCULATE_MARKET_ORDER_FAILURE',
  CALCULATE_MARKET_ORDER_CLEAR: 'CALCULATE_MARKET_ORDER_CLEAR',

  // ----- // POST_CALCULATE_LIMIT_ORDER // ----- //
  POST_CALCULATE_LIMIT_ORDER_START: 'POST_CALCULATE_LIMIT_ORDER_START',
  POST_CALCULATE_LIMIT_ORDER_SUCCESS: 'POST_CALCULATE_LIMIT_ORDER_SUCCESS',
  POST_CALCULATE_LIMIT_ORDER_FAILURE: 'POST_CALCULATE_LIMIT_ORDER_FAILURE',
  POST_PUBLIC_CALCULATE_LIMIT_ORDER_START:
    'POST_PUBLIC_CALCULATE_LIMIT_ORDER_START',
  POST_PUBLIC_CALCULATE_LIMIT_ORDER_SUCCESS:
    'POST_PUBLIC_CALCULATE_LIMIT_ORDER_SUCCESS',
  POST_PUBLIC_CALCULATE_LIMIT_ORDER_FAILURE:
    'POST_PUBLIC_CALCULATE_LIMIT_ORDER_FAILURE',
  CALCULATE_LIMIT_ORDER_CLEAR: 'CALCULATE_LIMIT_ORDER_CLEAR',
  CLEAR_ALL_ORDERS_START: 'CLEAR_ALL_ORDERS_START',
  /**
   * DEPOSIT
   */

  // ----- // GET WALLETS LIST // ----- //
  GET_WALLETS_LIST_START: 'GET_WALLETS_LIST_START',
  GET_WALLETS_LIST_SUCCESS: 'GET_WALLETS_LIST_SUCCESS',
  GET_WALLETS_LIST_FAILURE: 'GET_WALLETS_LIST_FAILURE',
  UPDATE_WALLETS_LIST: 'UPDATE_WALLETS_LIST',

  // ----- // GET CRYPTO CURRENCY LIST // ----- //
  GET_CRYPTO_CURRENCY_LIST_START: 'GET_CRYPTO_CURRENCY_LIST_START',
  GET_CRYPTO_CURRENCY_LIST_SUCCESS: 'GET_CRYPTO_CURRENCY_LIST_SUCCESS',
  GET_CRYPTO_CURRENCY_LIST_FAILURE: 'GET_CRYPTO_CURRENCY_LIST_FAILURE',

  // ----- // GET FIAT DEPOSIT HISTORY // ----- //
  GET_FIAT_DEPOSIT_HISTORY_START: 'GET_FIAT_DEPOSIT_HISTORY_START',
  GET_FIAT_DEPOSIT_HISTORY_SUCCESS: 'GET_FIAT_DEPOSIT_HISTORY_SUCCESS',
  GET_FIAT_DEPOSIT_HISTORY_FAILURE: 'GET_FIAT_DEPOSIT_HISTORY_FAILURE',

  // ----- // GET CRYPTO FIAT DEPOSIT HISTORY // ----- //
  GET_CRYPTO_DEPOSIT_HISTORY_START: 'GET_CRYPTO_DEPOSIT_HISTORY_START',
  GET_CRYPTO_DEPOSIT_HISTORY_SUCCESS: 'GET_CRYPTO_DEPOSIT_HISTORY_SUCCESS',
  GET_CRYPTO_DEPOSIT_HISTORY_FAILURE: 'GET_CRYPTO_DEPOSIT_HISTORY_FAILURE',

  // ----- // GENERATE COIN ADRESS // ----- //
  GENERATE_COIN_ADRESS_START: 'START_GENERATE_COIN_ADRESS',
  GENERATE_COIN_ADRESS_SUCCESS: 'GENERATE_COIN_ADRESS_SUCCESS',
  GENERATE_COIN_ADRESS_FAILURE: 'GENERATE_COIN_ADRESS_FAILURE',

  /**
   * WITHDRAW
   */

  // ----- // GET WITHDRAW WHITELIST ADDRESSES // ----- //
  GET_WITHDRAW_WHITELIST_ADDRESSES_START:
    'GET_WITHDRAW_WHITELIST_ADDRESSES_START',
  GET_WITHDRAW_WHITELIST_ADDRESSES_SUCCESS:
    'GET_WITHDRAW_WHITELIST_ADDRESSES_SUCCESS',
  GET_WITHDRAW_WHITELIST_ADDRESSES_FAILURE:
    'GET_WITHDRAW_WHITELIST_ADDRESSES_FAILURE',

  // ----- // TOGGLE WITHDRAW WHITELIST ADDRESSES // ----- //
  TOGGLE_WITHDRAW_WHITELIST_ADDRESSES_START:
    'TOGGLE_WITHDRAW_WHITELIST_ADDRESSES_START',
  TOGGLE_WITHDRAW_WHITELIST_ADDRESSES_SUCCESS:
    'TOGGLE_WITHDRAW_WHITELIST_ADDRESSES_SUCCESS',
  TOGGLE_WITHDRAW_WHITELIST_ADDRESSES_FAILURE:
    'TOGGLE_WITHDRAW_WHITELIST_ADDRESSES_FAILURE',

  // ----- // UPDATE WITHDRAW WHITELIST ADDRESSES // ----- //
  UPDATE_WITHDRAW_WHITELIST_ADDRESSES_START:
    'UPDATE_WITHDRAW_WHITELIST_ADDRESSES_START',
  UPDATE_WITHDRAW_WHITELIST_ADDRESSES_SUCCESS:
    'UPDATE_WITHDRAW_WHITELIST_ADDRESSES_SUCCESS',
  UPDATE_WITHDRAW_WHITELIST_ADDRESSES_FAILURE:
    'UPDATE_WITHDRAW_WHITELIST_ADDRESSES_FAILURE',

  // ----- // CHECK USER VALID ADDRESS // ----- //
  CHECK_USER_VALID_ADDRESS_START: 'CHECK_USER_VALID_ADDRESS_START',
  CHECK_USER_VALID_ADDRESS_SUCCESS: 'CHECK_USER_VALID_ADDRESS_SUCCESS',
  CHECK_USER_VALID_ADDRESS_FAILURE: 'CHECK_USER_VALID_ADDRESS_FAILURE',

  // ----- // POST CRYPTO WITHDRAW // ----- //
  POST_CRYPTO_WITHDRAW_START: 'POST_CRYPTO_WITHDRAW_START',
  POST_CRYPTO_WITHDRAW_SUCCESS: 'POST_CRYPTO_WITHDRAW_SUCCESS',
  POST_CRYPTO_WITHDRAW_FAILURE: 'POST_CRYPTO_WITHDRAW_FAILURE',

  // ----- // POST FIAT BANKS WITHDRAW // ----- //
  POST_FIAT_BANKS_WITHDRAW_START: 'POST_FIAT_BANKS_WITHDRAW_START',
  POST_FIAT_BANKS_WITHDRAW_SUCCESS: 'POST_FIAT_BANKS_WITHDRAW_SUCCESS',
  POST_FIAT_BANKS_WITHDRAW_FAILURE: 'POST_FIAT_BANKS_WITHDRAW_FAILURE',

  // ----- // PAYMENT AGENT POST FIAT BANKS WITHDRAW // ----- //
  POST_PAYMENT_AGENT_FIAT_BANKS_WITHDRAW_START:
    'POST_PAYMENT_AGENT_FIAT_BANKS_WITHDRAW_START',
  POST_PAYMENT_AGENT_FIAT_BANKS_WITHDRAW_SUCCESS:
    'POST_PAYMENT_AGENT_FIAT_BANKS_WITHDRAW_SUCCESS',
  POST_PAYMENT_AGENT_FIAT_BANKS_WITHDRAW_FAILURE:
    'POST_PAYMENT_AGENT_FIAT_BANKS_WITHDRAW_FAILURE',

  // ----- // GET WITHDRAW AMOUNT IN USD// ----- //
  GET_WITHDRAW_AMOUNT_IN_USD_START: 'GET_WITHDRAW_AMOUNT_IN_USD_START',
  GET_WITHDRAW_AMOUNT_IN_USD_SUCCESS: 'GET_WITHDRAW_AMOUNT_IN_USD_SUCCESS',
  GET_WITHDRAW_AMOUNT_IN_USD_FAILURE: 'GET_WITHDRAW_AMOUNT_IN_USD_FAILURE',

  // ----- // GET FIAT WITHDRAW HISTORY // ----- //
  GET_FIAT_WITHDRAW_HISTORY_START: 'GET_FIAT_WITHDRAW_HISTORY_START',
  GET_FIAT_WITHDRAW_HISTORY_SUCCESS: 'GET_FIAT_WITHDRAW_HISTORY_SUCCESS',
  GET_FIAT_WITHDRAW_HISTORY_FAILURE: 'GET_FIAT_WITHDRAW_HISTORY_FAILURE',

  // ----- // GET CRYPTO WITHDRAW HISTORY // ----- //
  GET_CRYPTO_WITHDRAW_HISTORY_START: 'GET_CRYPTO_WITHDRAW_HISTORY_START',
  GET_CRYPTO_WITHDRAW_HISTORY_SUCCESS: 'GET_CRYPTO_WITHDRAW_HISTORY_SUCCESS',
  GET_CRYPTO_WITHDRAW_HISTORY_FAILURE: 'GET_CRYPTO_WITHDRAW_HISTORY_FAILURE',

  // ----- // GET ALL DEPOSIT HISTORY // ----- //
  GET_DEPOSIT_HISTORY_START: 'GET_DEPOSIT_HISTORY_START',
  GET_DEPOSIT_HISTORY_SUCCESS: 'GET_DEPOSIT_HISTORY_SUCCESS',
  GET_DEPOSIT_HISTORY_FAILURE: 'GET_DEPOSIT_HISTORY_FAILURE',

  // ----- // GET ALL WITHDRAWAL HISTORY // ----- //
  GET_WITHDRAWAL_HISTORY_START: 'GET_WITHDRAWAL_HISTORY_START',
  GET_WITHDRAWAL_HISTORY_SUCCESS: 'GET_WITHDRAWAL_HISTORY_SUCCESS',
  GET_WITHDRAWAL_HISTORY_FAILURE: 'GET_WITHDRAWAL_HISTORY_FAILURE',

  // ----- // CLEAR ALL HISTORY // ----- //
  CLEAR_ALL_HISTORY_START: 'CLEAR_ALL_HISTORY_START',
  CLEAR_ALL_HISTORY_SUCCESS: 'CLEAR_ALL_HISTORY_SUCCESS',
  CLEAR_ALL_HISTORY_FAILURE: 'CLEAR_ALL_HISTORY_FAILURE',

  // ----- // CREATE OZOW REQUEST // ----- //
  CREATE_OZOW_REQUEST_START: 'CREATE_OZOW_REQUEST_START',
  CREATE_OZOW_REQUEST_SUCCESS: 'CREATE_OZOW_REQUEST_SUCCESS',
  CREATE_OZOW_REQUEST_FAILURE: 'CREATE_OZOW_REQUEST_FAILURE',

  // ----- // CREATE BANK REQUEST // ----- //
  CREATE_BANK_REQUEST_START: 'CREATE_BANK_REQUEST_START',
  CREATE_BANK_REQUEST_SUCCESS: 'CREATE_BANK_REQUEST_SUCCESS',
  CREATE_BANK_REQUEST_FAILURE: 'CREATE_BANK_REQUEST_FAILURE',

  SEND_BANK_INFO_TO_EMAIL_START: 'SEND_BANK_INFO_TO_EMAIL_START',

  // ----- // CREATE PAYMENT AGENT DEPOSIT FIAT // ----- //
  CREATE_PAYMENT_AGENT_DEPOSIT_FIAT_START:
    'CREATE_PAYMENT_AGENT_DEPOSIT_FIAT_START',
  CREATE_PAYMENT_AGENT_DEPOSIT_FIAT_SUCCESS:
    'CREATE_PAYMENT_AGENT_DEPOSIT_FIAT_SUCCESS',
  CREATE_PAYMENT_AGENT_DEPOSIT_FIAT_FAILURE:
    'CREATE_PAYMENT_AGENT_DEPOSIT_FIAT_FAILURE',

  // ----- // SUBMIT INVESTMENT FORM // ----- //
  INVESTMENT_FORM_SEND_START: 'INVESTMENT_FORM_SEND_START',

  // ----- // SUMSUB // ----- //
  GET_SUMSUB_TOKEN_START: 'GET_SUMSUB_TOKEN_START',
  GET_SUMSUB_TOKEN_SUCCESS: 'GET_SUMSUB_TOKEN_SUCCESS',
  GET_SUMSUB_TOKEN_FAILURE: 'GET_SUMSUB_TOKEN_FAILURE',

  // ----- // GET REFERRAL INFO // ----- //
  GET_REFERRAL_INFO_START: 'GET_REFERRAL_INFO_START',
  GET_REFERRAL_INFO_SUCCESS: 'GET_REFERRAL_INFO_SUCCESS',
  GET_REFERRAL_INFO_FAILURE: 'GET_REFERRAL_INFO_FAILURE',

  // ----- // GET LIST REFERRAL DEDUCTIONS // ----- //
  GET_LIST_REFERRAL_DEDUCTIONS_START: 'GET_LIST_REFERRAL_DEDUCTIONS_START',
  GET_LIST_REFERRAL_DEDUCTIONS_SUCCESS: 'GET_LIST_REFERRAL_DEDUCTIONS_SUCCESS',
  GET_LIST_REFERRAL_DEDUCTIONS_FAILURE: 'GET_LIST_REFERRAL_DEDUCTIONS_FAILURE',

  // ----- // CLEAR LIST REFERRAL DEDUCTIONS // ----- //
  CLEAR_LIST_REFERRAL_DEDUCTIONS: 'CLEAR_LIST_REFERRAL_DEDUCTIONS',

  // ----- // GET REFERRAL RATINGS // ----- //
  GET_REFERRAL_RATINGS_START: 'GET_REFERRAL_RATINGS_START',
  GET_REFERRAL_RATINGS_SUCCESS: 'GET_REFERRAL_RATINGS_SUCCESS',
  GET_REFERRAL_RATINGS_FAILURE: 'GET_REFERRAL_RATINGS_FAILURE',

  // ----- // CLEAR REFERRAL RATINGS TABLE // ----- //
  CLEAR_REFERRAL_RATINGS: 'CLEAR_REFERRAL_RATINGS',

  // ----- // GET DBA ANALYSIS // ----- //
  GET_DBA_ANALYSIS_START: 'GET_DBA_ANALYSIS_START',
  GET_DBA_ANALYSIS_SUCCESS: 'GET_DBA_ANALYSIS_SUCCESS',
  GET_DBA_ANALYSIS_FAILURE: 'GET_DBA_ANALYSIS_FAILURE',

  // ----- // GET DBA INFORMATION // ----- //
  GET_DBA_INFORMATION_START: 'GET_DBA_INFORMATION_START',
  GET_DBA_INFORMATION_SUCCESS: 'GET_DBA_INFORMATION_SUCCESS',
  GET_DBA_INFORMATION_FAILURE: 'GET_DBA_INFORMATION_FAILURE',

  // ----- // GET PAYMENT METHODS START // ----- //
  GET_PAYMENT_METHODS_START: 'GET_PAYMENT_METHODS_START',
  GET_PAYMENT_METHODS_SUCCESS: 'GET_PAYMENT_METHODS_SUCCESS',
  GET_PAYMENT_METHODS_FAILURE: 'GET_PAYMENT_METHODS_FAILURE',

  // SEND BUY DBA FORM
  CHECK_DBA_START: 'CHECK_DBA_START',
  CHECK_DBA_SUCCESS: 'CHECK_DBA_SUCCESS',
  CHECK_DBA_FAILURE: 'CHECK_DBA_FAILURE',
  CHECK_DBA_CLEAR_STEP: 'CHECK_DBA_CLEAR_STEP',

  BUY_DBA_START: 'BUY_DBA_START',
  BUY_DBA_SUCCESS: 'BUY_DBA_SUCCESS',
  BUY_DBA_CLEAR: 'BUY_DBA_CLEAR',

  // CIRCLE
  GET_CIRCLE_PUBLIC_KEY_START: 'GET_CIRCLE_PUBLIC_KEY_START',
  GET_CIRCLE_PUBLIC_KEY_SUCCESS: 'GET_CIRCLE_PUBLIC_KEY_SUCCESS',
  GET_CIRCLE_PUBLIC_KEY_FAILURE: 'GET_CIRCLE_PUBLIC_KEY_FAILURE',

  CREATE_CIRCLE_CARD_START: 'CREATE_CIRCLE_CARD_START',
  CREATE_CIRCLE_CARD_SUCCESS: 'CREATE_CIRCLE_CARD_SUCCESS',
  CREATE_CIRCLE_CARD_FAILURE: 'CREATE_CIRCLE_CARD_FAILURE',

  CREATE_CIRCLE_PAYMENT_START: 'CREATE_CIRCLE_PAYMENT_START',
  CREATE_CIRCLE_PAYMENT_SUCCESS: 'CREATE_CIRCLE_PAYMENT_SUCCESS',
  CREATE_CIRCLE_PAYMENT_FAILURE: 'CREATE_CIRCLE_PAYMENT_FAILURE',

  /**
   * PAYMENT AGENT
   */

  // ----- // GET PUBLIC PAYMENT AGENTS LIST // ----- //
  GET_PUBLIC_PAYMENT_AGENTS_LIST_START: 'GET_PUBLIC_PAYMENT_AGENTS_LIST_START',
  GET_PUBLIC_PAYMENT_AGENTS_LIST_SUCCESS:
    'GET_PUBLIC_PAYMENT_AGENTS_LIST_SUCCESS',
  GET_PUBLIC_PAYMENT_AGENTS_LIST_FAILURE:
    'GET_PUBLIC_PAYMENT_AGENTS_LIST_FAILURE',
  CLEAR_ALL_PUBLIC_PAYMENT_AGENTS_LIST: 'CLEAR_ALL_PUBLIC_PAYMENT_AGENTS_LIST',

  // ----- // GET PRIVATE PAYMENT AGENTS LIST // ----- //
  GET_PRIVATE_PAYMENT_AGENTS_LIST_START:
    'GET_PRIVATE_PAYMENT_AGENTS_LIST_START',
  GET_PRIVATE_PAYMENT_AGENTS_LIST_SUCCESS:
    'GET_PRIVATE_PAYMENT_AGENTS_LIST_SUCCESS',
  GET_PRIVATE_PAYMENT_AGENTS_LIST_FAILURE:
    'GET_PRIVATE_PAYMENT_AGENTS_LIST_FAILURE',

  // ----- // GET SINGLE PAYMENT AGENT // ----- //
  GET_SINGLE_PAYMENT_AGENT_START: 'GET_SINGLE_PAYMENT_AGENT_START',
  GET_SINGLE_PAYMENT_AGENT_SUCCESS: 'GET_SINGLE_PAYMENT_AGENT_SUCCESS',
  GET_SINGLE_PAYMENT_AGENT_FAILURE: 'GET_SINGLE_PAYMENT_AGENT_FAILURE',

  // ----- // CALCULATE PAYMENT AGENT COMMISSION // ----- //
  CALCULATE_PAYMENT_AGENT_COMMISSION_START:
    'CALCULATE_PAYMENT_AGENT_COMMISSION_START',
  CALCULATE_PAYMENT_AGENT_COMMISSION_SUCCESS:
    'CALCULATE_PAYMENT_AGENT_COMMISSION_SUCCESS',
  CALCULATE_PAYMENT_AGENT_COMMISSION_FAILURE:
    'CALCULATE_PAYMENT_AGENT_COMMISSION_FAILURE',

  // ----- // REGISTER PAYMENT AGENT // ----- //
  REGISTER_PAYMENT_AGENT_START: 'REGISTER_PAYMENT_AGENT_START',
  REGISTER_PAYMENT_AGENT_SUCCESS: 'REGISTER_PAYMENT_AGENT_SUCCESS',
  REGISTER_PAYMENT_AGENT_FAILURE: 'REGISTER_PAYMENT_AGENT_FAILURE',

  // ----- // GET PAYMENT AGENT WITHDRAWAL LIST // ----- //
  GET_PAYMENT_AGENT_WITHDRAWAL_LIST_START:
    'GET_PAYMENT_AGENT_WITHDRAWAL_LIST_START',
  GET_PAYMENT_AGENT_WITHDRAWAL_LIST_SUCCESS:
    'GET_PAYMENT_AGENT_WITHDRAWAL_LIST_SUCCESS',
  GET_PAYMENT_AGENT_WITHDRAWAL_LIST_FAILURE:
    'GET_PAYMENT_AGENT_WITHDRAWAL_LIST_FAILURE',
  CLEAR_PAYMENT_AGENT_WITHDRAWAL_LIST: 'CLEAR_PAYMENT_AGENT_WITHDRAWAL_LIST',

  // ----- // UPDATE PAYMENT AGENT WITHDRAWAL STATUS // ----- //
  UPDATE_PAYMENT_AGENT_WITHDRAWAL_STATUS_START:
    'UPDATE_PAYMENT_AGENT_WITHDRAWAL_STATUS_START',
  UPDATE_PAYMENT_AGENT_WITHDRAWAL_STATUS_SUCCESS:
    'UPDATE_PAYMENT_AGENT_WITHDRAWAL_STATUS_SUCCESS',
  UPDATE_PAYMENT_AGENT_WITHDRAWAL_STATUS_FAILURE:
    'UPDATE_PAYMENT_AGENT_WITHDRAWAL_STATUS_FAILURE',

  // ----- // GET PAYMENT AGENT TRANSFER LIST // ----- //
  GET_PAYMENT_AGENT_TRANSFER_LIST_START:
    'GET_PAYMENT_AGENT_TRANSFER_LIST_START',
  GET_PAYMENT_AGENT_TRANSFER_LIST_SUCCESS:
    'GET_PAYMENT_AGENT_TRANSFER_LIST_SUCCESS',
  GET_PAYMENT_AGENT_TRANSFER_LIST_FAILURE:
    'GET_PAYMENT_AGENT_TRANSFER_LIST_FAILURE',
  CLEAR_PAYMENT_AGENT_TRANSFER_LIST: 'CLEAR_PAYMENT_AGENT_TRANSFER_LIST',

  // ----- // EDIT PAYMENT AGENT // ----- //
  EDIT_PAYMENT_AGENT_START: 'EDIT_PAYMENT_AGENT_START',
  EDIT_PAYMENT_AGENT_SUCCESS: 'EDIT_PAYMENT_AGENT_SUCCESS',
  EDIT_PAYMENT_AGENT_FAILURE: 'EDIT_PAYMENT_AGENT_FAILURE',

  // ----- // GET COUNTRIES DATA // ----- //
  GET_COUNTRIES_DATA_START: 'GET_COUNTRIES_DATA_START',
  GET_COUNTRIES_DATA_SUCCESS: 'GET_COUNTRIES_DATA_SUCCESS',
  GET_COUNTRIES_DATA_FAILURE: 'GET_COUNTRIES_DATA_FAILURE',

  // ----- // GET MARKETS DATA // ----- //
  GET_MARKETS_DATA_START: 'GET_MARKETS_DATA_START',
  GET_MARKETS_DATA_SUCCESS: 'GET_MARKETS_DATA_SUCCESS',
  GET_MARKETS_DATA_FAILURE: 'GET_MARKETS_DATA_FAILURE',
  UPDATE_MARKETS: 'UPDATE_MARKETS',

  // ----- // MAKE DAFRIBANK PAYMENT // ----- //
  MAKE_DAFRIBANK_PAYMENT_START: 'MAKE_DAFRIBANK_PAYMENT_START',
  MAKE_DAFRIBANK_PAYMENT_SUCCESS: 'MAKE_DAFRIBANK_PAYMENT_SUCCESS',
  MAKE_DAFRIBANK_PAYMENT_FAILURE: 'MAKE_DAFRIBANK_PAYMENT_FAILURE',
};
