import React from 'react';
import L from 'i18n-react';

const Privacy = () => {
  return (
    <section className="content-section">
      <div className="custom-container">
        <h2 className="section-title section-title--center">
          {L.translate('Pages.Statics.Terms&Conditions.item1')}
        </h2>
        <div className="text-content-wrapper">
          <div className="text-content-block">
            <h2 className="text-content-title">
              {L.translate('Pages.Statics.Terms&Conditions.item2')}
            </h2>
            <h3>{L.translate('Pages.Statics.Terms&Conditions.item3')}</h3>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item4')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item5')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item6')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item7')}</p>
            <h3>{L.translate('Pages.Statics.Terms&Conditions.item8')}</h3>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item9')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item10')}</p>
            <h3>{L.translate('Pages.Statics.Terms&Conditions.item11')}</h3>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item12')}</p>
            <ul>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item13')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item14')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item15')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item16')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item17')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item18')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item19')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item20')}</li>
            </ul>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item21')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item22')}</p>
            <h3>{L.translate('Pages.Statics.Terms&Conditions.item23')}</h3>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item24')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item25')}</p>
            <h3>{L.translate('Pages.Statics.Terms&Conditions.item26')}</h3>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item27')}</p>
            <ul>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item28')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item29')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item30')}</li>
            </ul>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item31')}</p>
            <h3>{L.translate('Pages.Statics.Terms&Conditions.item32')}</h3>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item33')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item34')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item35')}</p>
            <ul>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item36')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item37')}</li>
            </ul>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item38')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item39')}</p>
            <h3>{L.translate('Pages.Statics.Terms&Conditions.item40')}</h3>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item41')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item42')}</p>
            <ul>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item43')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item44')}</li>
            </ul>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item45')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item46')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item47')}</p>
            <ul>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item48')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item49')}</li>
            </ul>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item50')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item51')}</p>
            <h3>{L.translate('Pages.Statics.Terms&Conditions.item52')}</h3>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item53')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item54')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item55')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item56')}</p>
            <ul>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item57')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item58')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item59')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item60')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item61')}</li>
            </ul>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item62')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item63')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item64')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item65')}</p>

            <h3>{L.translate('Pages.Statics.Terms&Conditions.item66')}</h3>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item67')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item68')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item69')}</p>
            <h3>{L.translate('Pages.Statics.Terms&Conditions.item70')}</h3>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item71')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item72')}</p>
            <ul>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item73')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item74')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item75')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item76')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item77')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item78')}</li>
            </ul>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item79')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item80')}</p>
            <h3>{L.translate('Pages.Statics.Terms&Conditions.item81')}</h3>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item82')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item83')}</p>
            <ul>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item84')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item85')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item86')}</li>
            </ul>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item87')}</p>
            <h3>{L.translate('Pages.Statics.Terms&Conditions.item88')}</h3>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item89')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item90')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item91')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item92')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item93')}</p>
            <h3>{L.translate('Pages.Statics.Terms&Conditions.item94')}</h3>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item95')}</p>
            <ul>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item96')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item97')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item98')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item99')}</li>
            </ul>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item100')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item101')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item102')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item103')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item104')}</p>
            <ul>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item105')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item106')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item107')}</li>
            </ul>
            <h3>{L.translate('Pages.Statics.Terms&Conditions.item108')}</h3>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item109')}</p>
            <h3>{L.translate('Pages.Statics.Terms&Conditions.item110')}</h3>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item111')}</p>
            <ul>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item112')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item113')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item114')}</li>
            </ul>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item115')}</p>
            <ul>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item116')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item117')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item118')}</li>
            </ul>
            <h3>{L.translate('Pages.Statics.Terms&Conditions.item119')}</h3>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item120')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item121')}</p>
            <h3>{L.translate('Pages.Statics.Terms&Conditions.item122')}</h3>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item123')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item124')}</p>
            <ul>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item125')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item126')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item127')}</li>
            </ul>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item128')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item129')}</p>
            <h3>{L.translate('Pages.Statics.Terms&Conditions.item130')}</h3>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item131')}</p>
            <ul>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item132')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item133')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item134')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item135')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item136')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item137')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item138')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item139')}</li>
            </ul>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item140')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item141')}</p>
            <ul>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item142')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item143')}</li>
            </ul>
            <h3>{L.translate('Pages.Statics.Terms&Conditions.item144')}</h3>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item145')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item146')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item147')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item148')}</p>
            <h3>{L.translate('Pages.Statics.Terms&Conditions.item149')}</h3>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item150')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item151')}</p>
            <h3>{L.translate('Pages.Statics.Terms&Conditions.item152')}</h3>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item153')}</p>
            <h3>{L.translate('Pages.Statics.Terms&Conditions.item154')}</h3>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item155')}</p>
            <ul>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item156')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item157')}</li>
            </ul>
            <h3>{L.translate('Pages.Statics.Terms&Conditions.item158')}</h3>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item159')}</p>
            <ul>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item160')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item161')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item162')}</li>
            </ul>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item163')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item164')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item165')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item166')}</p>
            <ul>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item167')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item168')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item169')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item170')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item171')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item172')}</li>
            </ul>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item173')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item174')}</p>
            <ul>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item175')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item176')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item177')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item178')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item179')}</li>
            </ul>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item180')}</p>
            <h3>{L.translate('Pages.Statics.Terms&Conditions.item181')}</h3>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item182')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item183')}</p>
            <h3>{L.translate('Pages.Statics.Terms&Conditions.item184')}</h3>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item185')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item186')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item187')}</p>
            <h3>{L.translate('Pages.Statics.Terms&Conditions.item188')}</h3>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item189')}</p>
            <h3>{L.translate('Pages.Statics.Terms&Conditions.item190')}</h3>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item191')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item192')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item193')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item194')}</p>
            <h3>{L.translate('Pages.Statics.Terms&Conditions.item195')}</h3>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item196')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item197')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item198')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item199')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item200')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item201')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item202')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item203')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item204')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item205')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item206')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item207')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item208')}</p>
            <ul>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item209')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item210')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item211')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item212')}</li>
            </ul>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item213')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item214')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item215')}</p>
            <h3>{L.translate('Pages.Statics.Terms&Conditions.item216')}</h3>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item217')}</p>
            <ul>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item218')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item219')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item220')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item221')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item222')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item223')}</li>
              <li>{L.translate('Pages.Statics.Terms&Conditions.item224')}</li>
            </ul>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item225')}</p>
            <h3>{L.translate('Pages.Statics.Terms&Conditions.item226')}</h3>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item227')}</p>
            <p>{L.translate('Pages.Statics.Terms&Conditions.item228')}</p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Privacy;
